# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=150)),
                ('value', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=150)),
                ('creationDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('email', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('email', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
