# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipz', '0002_auto_20161026_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tipz.Project'),
        ),
    ]
